interface SdkErrors {
  [key: number]: string;
}

export const StarnameErrors: SdkErrors = {
  1: "domain name provided is invalid",
  2: "domain already exists",
  3: "operation unauthorized",
  5: "domain does not exist",
  6: "account does not exist",
  7: "account has expired",
  8: "invalid owner",
  9: "invalid account name",
  10: "resource provided is not valid",
  11: "domain has expired",
  12: "domain has not expired",
  13: "account already exists",
  14: "malformed request",
  15: "certificate already exists",
  16: "certificate does not exist",
  17: "domain grace period has not finished",
  18: "invalid domain type",
  19: "invalid registerer",
  20: "account name provided cannot be empty",
  21: "account grace period has not finished",
  22: "resource limit exceeded",
  23: "certificate size exceeded",
  24: "certificate limit reached",
  25: "metadata size exceeded",
  26: "accounts in closed domains do not expire",
  27: "max renew exceeded",
  31: "renewal deadline was exceeded",
};

export const EscrowErrors: SdkErrors = {
  1: "The escrow should be in open state",
  2: "The generated escrow ID is not unique",
  3: "The escrow ID is not valid",
  4: "This escrow does not exists",
  5: "This escrow is expired",
  6: "The provided amount is invalid",
  7: "The transfer amount is lower than the defined price",
  8: "The object type ID is unknown",
  9: "The object does not exist",
  10: "This account cannot be used in an escrow",
  11: "The deadline has passed",
  12: "No fields have been filled : nothing to update",
  13: "The broker commission must be a number between 0 and 1",
  14: "The price is invalid",
  15: "The deadline is invalid",
};

export const CosmosErrors: SdkErrors = {
  2: "tx parse error",
  3: "invalid sequence",
  4: "unauthorized",
  5: "insufficient funds",
  6: "unknown request",
  7: "invalid address",
  8: "invalid pubkey",
  9: "unknown address",
  10: "invalid coins",
  11: "out of gas",
  12: "memo too large",
  13: "insufficient fee",
  14: "maximum number of signatures exceeded",
  15: "no signatures supplied",
  16: "failed to marshal JSON bytes",
  17: "failed to unmarshal JSON bytes",
  18: "invalid request",
  19: "tx already in mempool",
  20: "mempool is full",
  21: "tx too large",
  22: "key not found",
  24: "tx intented signer does not match the given signer",
  25: "invalid gas adjustment",
  26: "invalid height",
  27: "invalid version",
  28: "invalid chain-id",
  29: "invalid type",
  32: "incorrect account sequence",
  38: "not found",
  41: "invalid gas limit",
};
